### ISSUE TITLE
Search interface improvement

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#79] opened 2016-04-11 15:03 UTC
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

It is not clear why related searches are showing some topics -- if a feature is not yet implemented it's better not to show search suggestions. Unchecking a box takes a long time, and so does a browser back button. I suggest to have some elements of twinlist: http://www.cs.umd.edu/hcil/sharp/twinlist/

**Comment by RuilingLiu** [comment] 2016-04-14 19:05
Thank you for your suggestions. The related searches panel has been removed.
Which elements of twinlist do you suggest?

**Comment by tjohnson250** [comment] 2016-07-25 20:40
I don't really understand what the issue is here nor how we could adopt parts of twinist. Twinlist is for reconciling two (or three) lists of items when those lists are relatively short.

**Comment by RuilingLiu** [comment] 2016-08-30 16:44
An email has been sent to the issue reporter a week ago. But we didn't get a reply. We will close this issue for now.

**Closed as completed by RuilingLiu** 2016-08-30 16:44 UTC
Labels: v0.5, Usability
