### ISSUE TITLE
PDB Ranking Issue

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#43] opened 2016-03-15 18:44 UTC
This issue has been reported by Greg Farber.

I received an e-mail asking me to look at the v0.5 interface. I tried a few queries, and I was not terribly impressed. The PDB is listed as a repository that is indexed by BioCADDIE. When "xylose isomerase" was entered, nothing showed up even though there are more than 100 entries in the PDB for this molecule. A search on autism and data repositories did show some repositories, but the amount of information about autism in the repositories varied tremendously. The last issue is very significant. How will the results be ranked once the infrastructure is open to the public?

**Comment by saeid-p** [comment] 2016-03-15 18:48
Answered by @RuilingLiu 

Hi Greg,

Thank you so much for your feedbacks!
1. When xylose isomerase was entered, nothing showed up even though there are more than 100 entries in the PDB for this molecule. When xylose isomerase was entered, there were 125 entries in PDB. Do you mean that these entries were not what you expected?
   Please refer to this page: http://datamed.biocaddie.org/search.php?query=xylose%20isomerase&searchtype=data&offset=1&repository=0002
2. A search on autism and data repositories did show some repositories, but the amount of information about autism in the repositories varied tremendously. When we ingested the metadata from the repositories,  the numbers of data sets in the repositories varied tremendously. For example, there are 192,501 data sets in ClinicalTrials.gov repository, there are only 236 data sets in MPD repository. 
   That's why the amount of information in the repositories varied tremendously.
3. How will the results be ranked once the infrastructure is open to the public?
   In our current version, the results are ranked using Elasticsearch¹s default ranking algorithm. In our future release, we will track the users selections and refine the ranking results based on their selections.

Please let us know if you have any further questions.

**Comment by ianfore** [comment] 2016-03-17 17:29
What are the criteria for closing an issue. We really need to check in with the people who raise an issue as to whether it is "closed" in their mind. Did we get any response from Greg? 

Also - which issue is this a duplicate of?

**Comment by RuilingLiu** [comment] 2016-03-17 19:18
Saeid separated this issue and reported them in #45 #46 #47 because it's easier for us to close the issues as we address each of them.It seems that GitHub issues cannot be deleted so he marked it as "Duplicate".

Greg emailed us his feedback and we already replied to his email. We haven't gotten any response from him.

**Comment by saeid-p** [comment] 2016-03-18 17:38
Hi Ian,

I hope Ruiling explanation was explanatory enough for this ticket. I mistakenly posted all three issues together. Then I separated then into three different thread.

Best,
Saeid

**Comment by ianfore** [comment] 2016-03-21 13:10
Reclosing - now I understand better what happened. When an issue is closed it always helps to communicate why it was closed.

Links to the replacement issues here I hope. Will pick up the dialog in each thread separately.
[45](https://github.com/biocaddie/prototype_issues/issues/45)
[46](https://github.com/biocaddie/prototype_issues/issues/46)
[47](https://github.com/biocaddie/prototype_issues/issues/47)

**Closed as completed by ianfore** 2016-03-21 13:10 UTC
Labels: Duplicate
