### ISSUE TITLE
LINCS: KINOMEScan is not gene expression (bioCADDIE data type)

### ISSUE THREAD

**Issue by chung88** [biocaddie/prototype_issues#42] opened 2016-03-14 15:55 UTC
In bioCADDIE LINCS is under the "Gene Expression"  data type.  KINOMEScan is a biochemical profiling assay for kinase inhibitor drug discovery, not a gene expression assay.

LINCS has several data types.

I am guessing the following are the 10 data types:
 Clinical Trials (43152)
 Unspecified (30619)
 Gene Expression (11437)
 Nucleotide Sequence (1391)
 Protein Structure (153)
 Imaging Data (56)
 Morphology (33)
 Phenotype (22)
 Proteomics Data (13)
 Physiological Signals (10)

Steps:
1.-  Search term "KINOMEScan"
2.-  Returns:
http://datamed.biocaddie.org/search.php?query=KINOMEScan&searchtype=data
3.-  Under Data Types  Gene Expression (158)

Gene Expression (158)
GEO (0)
LINCS (158)
GEMMA (0)
ArrayExpress (0)

**Comment by aegururaj** [comment] 2016-03-14 18:14
Caty, currently we are tagging data types to the repositories. If LINCS has several data types, then we'll tag it as unspecified. Thanks for pointing this to us. On the same note, do you have tags for data types to each dataset? If yes, what ontology are you using to do this?

**Comment by RuilingLiu** [comment] 2016-03-15 15:11
The data type of "LINCS" repository has been changed to "Unspecified"

**Comment by chung88** [comment] 2016-03-15 16:12
The UI filter box "Data Type" and the table "Data Type" are not the same.  The data type in the table (step 4) is better than unspecified.

Steps:
1.-  Search term:  KINOMEScan
2.-  Filter box shows
Data Types: Unspecified (158) 
View [search results](http://datamed.biocaddie.org/search.php?query=kinomescan&searchtype=data)
3.-  Click on "LINCS" tag
4.-  View content on the table
DataType:  Biochemical Protein binding profile 
View [table](http://datamed.biocaddie.org/search-repository.php?query=kinomescan&repository=0004&searchtype=data)

**Comment by RuilingLiu** [comment] 2016-03-15 21:21
The "Unspecified" is the type of the LINCS repository.

The data type in the table is the type of each data set in LINCS. We can use it as a filter for LINCS data sets since not every repository has tagged data types to their data sets.

**Comment by RuilingLiu** [comment] 2016-09-16 19:53
Hi @chung88 
Is the resolution of the issue appropriate? Is it OK for us to close this issue?

**Comment by chung88** [comment] 2016-09-16 19:59
You can merge this issue with other issues that connect into a discussion to improve the bioCaddie term "data type", in LINCS it is the "Subject Domain Area".

**Comment by RuilingLiu** [comment] 2016-09-16 20:08
Duplicate of issue #143

**Closed as completed by RuilingLiu** 2016-09-16 20:08 UTC
Labels: v0.5
