### ISSUE TITLE
why the numbers for data sets differ from actual sites

### ISSUE THREAD

**Issue by dianneusa** [biocaddie/prototype_issues#100] opened 2016-05-05 16:32 UTC
For instance, 

CT.gov has 214,105 studies. Datamed: Displaying 192501 results for "ClinicalTrials". 
Entrez Bioproject: all[sb]: Items: 1 to 20 of 174826. Datamed: Displaying 155851 results for "BioProject"
I would expect the data to be pulled via an API and therefore in sync.

**Comment by jgrethe** [comment] 2016-05-10 20:00
This seems to be a duplicate of #93 - Adding response from that ticket here as well:

Yes, we do pull the data from a repository's API or download. However, for the prototype, we only crawl the repositories at certain times (e.g. around releases) - so the index can end-up having different total counts (e.g. ClinicalTrials.gov is now at 215,060 studies).

**Closed as completed by jgrethe** 2016-05-10 20:00 UTC
Labels: Question, v0.5
