### ISSUE TITLE
Agreement to publish your logo in our paper

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#303] opened 2017-11-23 13:42 UTC
Dear DataMed,
    
We have a paper accepted for the publication in Nature Ecology & Evolution, where we describe the research data landscape, and how to navigate it, for the EcoEvo field.
    
In the Figure 1 we use your Logo. If you agree with the use of your logo, could you please send me an email to which I can send you the Figure in questions and the Image licence form to be signed?
    
 Very best and thank you for your time
   
 Antica Culina on behalf of all the outhors

**Comment by aegururaj** [comment] 2018-01-25 12:46
duplicate of #304

**Closed as completed by aegururaj** 2018-01-25 12:46 UTC
